version: '3.2'

services:

    mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw
      volumes:
        - ./volume/mysql/data:/var/lib/mysql
      ports:
        - "3306:3306"